version: '3.8'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 1G
    command: --default-authentication-plugin=mysql_native_password
